version: '3.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  api:
    container_name: emtec-library
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - library-net
    depends_on:
      - mysql

  mysql:
    container_name: db
    image: mysql
    networks:
      - library-net
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROD_DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ms2data:/var/lib/mysql

networks:
  library-net:
volumes:
  ms2data:
