version: '3.1'
services:
  mysql:
    container_name: emtec
    image: mysql
    env_file:
      - .env
    networks:
      - library-net
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROD_DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ms2data:/var/lib/mysql

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - library-net
    container_name: zookeeper

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    networks:
      - library-net
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  book-service:
    container_name: book-service
    image: book-service
    networks:
      - library-net
    depends_on:
      - mysql
      - kafka
      - zookeeper

  api-getway:
    container_name: emtec-library-api
    image: api-getway
    ports:
      - 3000:3000
    networks:
      - library-net
    depends_on:
      - book-service

networks:
  library-net:
volumes:
  ms2data:
